/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiket.view.authenticated;

import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tiket.controller.EventController;
import tiket.helper.DTHelper;
import tiket.model.Event;
import tiket.view.authenticated.event.StageForm;

/**
 *
 * @author fkrfd
 */
public class EventForm extends javax.swing.JFrame {

    private final EventController controller = new EventController();

    private final DTHelper dtHelper = new DTHelper();

    private DefaultTableModel tableModel;

    /**
     * Creates new form Event
     */
    public EventForm() {
        initComponents();

        setEventTable();
        resetInput();
    }

    private void timeOnly(KeyEvent event) {
        char c = event.getKeyChar();

        if (!(Character.isDigit(c)) && c != ':') {
            event.consume();
        }
    }

    private void showMessage(String message) {
        JOptionPane.showMessageDialog(null, message);
    }

    private void setEventTable() {
        Object[] tableHeader = {"ID", "Nama Event", "Lokasi", "Waktu Mulai", "Waktu Selesai"};
        tableModel = new DefaultTableModel(null, tableHeader);
        tblEvent.setModel(tableModel);

        populateTable();
    }

    private void populateTable() {
        List<Event> events = controller.getAll();

        events.forEach((event) -> {
            Object[] data = {
                event.getId(),
                event.getName(),
                event.getLocation(),
                event.getStartedAt(),
                event.getFinishedAt()
            };

            tableModel.addRow(data);
        });
    }

    private void resetInput() {
        txtId.setText("");
        txtName.setText("");
        txtLocation.setText("");
        txtStartedDate.setDate(new Date());
        txtStartedTime.setText("");
        txtFinishedDate.setDate(new Date());
        txtFinishedTime.setText("");

        btnToStage.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtName = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLocation = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtStartedDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtStartedTime = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFinishedDate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtFinishedTime = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        eventBtnAdd = new javax.swing.JButton();
        eventBtnDelete = new javax.swing.JButton();
        eventBtnEdit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnToStage = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        txtId.setEditable(false);
        txtId.setColumns(20);
        txtId.setRows(1);
        txtId.setFocusable(false);
        txtId.setOpaque(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Manajemen Event");

        tblEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEvent);

        jLabel2.setText("Nama Event");

        txtName.setColumns(20);
        txtName.setRows(1);
        jScrollPane2.setViewportView(txtName);

        jLabel3.setText("Lokasi");

        txtLocation.setColumns(20);
        txtLocation.setRows(1);
        jScrollPane3.setViewportView(txtLocation);

        jLabel4.setText("Tanggal Mulai");

        txtStartedDate.setDateFormatString("yyyy-MM-dd");
        txtStartedDate.setMinSelectableDate(new Date());

        jLabel5.setText("Jam Mulai");

        txtStartedTime.setColumns(20);
        txtStartedTime.setRows(1);
        txtStartedTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStartedTimeKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(txtStartedTime);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Contoh: 00:00");

        jLabel7.setText("Tanggal Selesai");

        txtFinishedDate.setDateFormatString("yyyy-MM-dd");
        txtFinishedDate.setMinSelectableDate(new Date());

        jLabel8.setText("Jam Selesai");

        txtFinishedTime.setColumns(20);
        txtFinishedTime.setRows(1);
        txtFinishedTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFinishedTimeKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(txtFinishedTime);

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Contoh: 23:59");

        eventBtnAdd.setText("Tambah");
        eventBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventBtnAddActionPerformed(evt);
            }
        });

        eventBtnDelete.setText("Hapus");
        eventBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventBtnDeleteActionPerformed(evt);
            }
        });

        eventBtnEdit.setText("Ubah");
        eventBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventBtnEditActionPerformed(evt);
            }
        });

        jLabel10.setText("Dashboard >");

        btnToStage.setText("Manajemen Stage >");
        btnToStage.setEnabled(false);
        btnToStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToStageActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                        .addComponent(btnToStage)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtStartedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4)
                        .addComponent(txtFinishedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5)
                        .addComponent(eventBtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(eventBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(eventBtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(btnToStage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 502, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtStartedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFinishedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(eventBtnAdd)
                                .addComponent(eventBtnEdit))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eventBtnDelete)
                            .addGap(0, 37, Short.MAX_VALUE)))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStartedTimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStartedTimeKeyTyped
        timeOnly(evt);
    }//GEN-LAST:event_txtStartedTimeKeyTyped

    private void txtFinishedTimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFinishedTimeKeyTyped
        timeOnly(evt);
    }//GEN-LAST:event_txtFinishedTimeKeyTyped

    private void eventBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventBtnAddActionPerformed

        boolean response = controller.insert(txtName.getText(), txtLocation.getText(), txtStartedDate.getDate(), txtStartedTime.getText(), txtFinishedDate.getDate(), txtFinishedTime.getText());

        if (!response) {
            showMessage("Terjadi kesalahan saat menyimpan data, silahkan coba lagi");
            return;
        }

        showMessage("Berhasil menyimpan data");
        setEventTable();
        resetInput();
    }//GEN-LAST:event_eventBtnAddActionPerformed

    private void tblEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventMouseClicked
        int row = tblEvent.getSelectedRow();

        String id = tableModel.getValueAt(row, 0).toString();
        String name = tableModel.getValueAt(row, 1).toString();
        String location = tableModel.getValueAt(row, 2).toString();
        String startedAt = tableModel.getValueAt(row, 3).toString();
        String finishedAt = tableModel.getValueAt(row, 4).toString();

        String[] tempStartedAt = startedAt.split(" ");
        String[] tempFinishedAt = finishedAt.split(" ");

        Date startedDate = null;
        Date finishedDate = null;

        try {
            startedDate = new SimpleDateFormat("yyyy-MM-dd").parse(tempStartedAt[0]);
            finishedDate = new SimpleDateFormat("yyyy-MM-dd").parse(tempFinishedAt[0]);
        } catch (ParseException ex) {
            System.err.println(ex.getMessage());
        }

        String startedTime = dtHelper.setTimeFromDB(tempStartedAt[1]);
        String finishedTime = dtHelper.setTimeFromDB(tempFinishedAt[1]);

        txtId.setText(id);
        txtName.setText(name);
        txtLocation.setText(location);
        txtStartedDate.setDate(startedDate);
        txtStartedTime.setText(startedTime);
        txtFinishedDate.setDate(finishedDate);
        txtFinishedTime.setText(finishedTime);

        btnToStage.setEnabled(true);
    }//GEN-LAST:event_tblEventMouseClicked

    private void eventBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventBtnEditActionPerformed
        if (txtId.getText().equals("")) {
            showMessage("Anda harus memilih data terlebih dahulu");
            return;
        }

        String startedDate = dtHelper.formatMysqlDate(txtStartedDate.getDate());
        String finishedDate = dtHelper.formatMysqlDate(txtFinishedDate.getDate());

        String startedAt = startedDate + " " + txtStartedTime.getText();
        String finishedAt = finishedDate + " " + txtFinishedTime.getText();

        Event event = new Event();
        event.setId(new Integer(txtId.getText()));
        event.setName(txtName.getText());
        event.setLocation(txtLocation.getText());
        event.setStartedAt(startedAt);
        event.setFinishedAt(finishedAt);

        boolean response = controller.update(event);

        if (!response) {
            showMessage("Terjadi kesalahan saat mengubah data, silahkan coba lagi");
            return;
        }

        showMessage("Berhasil mengubah data");
        setEventTable();
        resetInput();
    }//GEN-LAST:event_eventBtnEditActionPerformed

    private void eventBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventBtnDeleteActionPerformed
        if (txtId.getText().equals("")) {
            showMessage("Anda harus memilih data terlebih dahulu");
            return;
        }

        boolean response = controller.delete(new Integer(txtId.getText()));

        if (!response) {
            showMessage("Terjadi kesalahan saat menghapus data, silahkan coba lagi");
            return;
        }

        showMessage("Berhasil menghapus data");
        setEventTable();
        resetInput();
    }//GEN-LAST:event_eventBtnDeleteActionPerformed

    private void btnToStageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToStageActionPerformed
        StageForm stageForm = new StageForm(new Integer(txtId.getText()));
        stageForm.setVisible(true);
    }//GEN-LAST:event_btnToStageActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetInput();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnToStage;
    private javax.swing.JButton eventBtnAdd;
    private javax.swing.JButton eventBtnDelete;
    private javax.swing.JButton eventBtnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblEvent;
    private com.toedter.calendar.JDateChooser txtFinishedDate;
    private javax.swing.JTextArea txtFinishedTime;
    private javax.swing.JTextArea txtId;
    private javax.swing.JTextArea txtLocation;
    private javax.swing.JTextArea txtName;
    private com.toedter.calendar.JDateChooser txtStartedDate;
    private javax.swing.JTextArea txtStartedTime;
    // End of variables declaration//GEN-END:variables
}
